### ISSUE TITLE
Design goals

### ISSUE THREAD

**Issue by JakobBD** [pik-piam/sodym#19]
It may make sense to have common understanding of what the package is supposed to be for, in order to derive design decisions from that. 
I am making a first draft, feel free to comment and we can update and expand the text in this comment.
Some of these goals are conflicting, and we will have to find a trade-off. 

**Target use and audience:** 
- Serve as a library basis for simson development 
- Serve as a library basis for other MFA's by external users.
  - Use cases and types of MFAs can be very diverse.
  - MFA users should not have to have a strong coding background to use this package.
  
**This leads to the following design goals: The package should be...** 
- As flexible as possible, in _how_ it can be used and _what_ it can be used for.
- As easy as possible to use, which includes
  - having few lines of code for a baseline/default case 
  - being able to use and to customize it without using complex coding patterns and tools.
    _Example: It should be possible to input and output the data in whatever format, selection and combination people like._  
  - The code being transparent about what it does, i.e. the lines written by the user hinting towards what's happening under the hood.
     _Example: We should only require them to implement subclasses where it has substantial benefits to the rest of the code._ 
- The package itself should be extensible in the future. I'm sure the need to extend it will arise. 
  _Example: Data paths should be given as an argument, not be pre-defined in the code_
- We should reduce package API changes to a minimum in the near future.
- Giving erroneous/unintended input should throw errors which make the problem clear to the user.
- Users should be able to fully learn how to use the package without looking at the source code, i.e. from documentation (Installation guide, API reference, examples)

**Comment by SallyDa** [comment]
Agree, once we have a version we are happy with, we can add versioning and make a pypi release. After this, we should ideally maintain backwards compatibility, and if/when we cannot then make a new major release with the breaking changes.

Regarding documentation, maybe we should think about something like a readthedocs page. What do you think?

**Comment by JakobBD** [comment]
Yes, pypi and readthedocs would be ideal.

**Comment by JakobBD** [comment]
Moved to wiki
