### ISSUE TITLE
Improve code of DynamicStockModel

### ISSUE THREAD

**Issue by SallyDa** [pik-piam/sodym#21]
Suggestions:
* different models depending on ldf_type?
* different models depending on lifetime model, inflow driven or stock driven?
* nicer method names or include an explanation of the naming system?

**Comment by JakobBD** [comment]
Most of above tasks are completed, still minor improvements.

Mainly: DSM-MFASystem interface? -> Checking and adapting dimensions when transforming from NamedDimArray to numpy array
