### ISSUE TITLE
split get_relative_mass_balance

### ISSUE THREAD

**Issue by JakobBD** [pik-piam/sodym#22]
The "total" shouldn't be in this function. 
Instead, there should be a function calling `get_mass_balance` and dividing it by a total.

**Comment by JakobBD** [comment]
Further: 

- check_mass_balance could be moved outside MFASystem (a helper function for example)

**Comment by SallyDa** [comment]
Started working on this #43 but I have a couple of questions on the existing logic (see also comments in the pr). I guess dividing by the "total" mass balance is just to give us an idea of how important any imbalances are? It's not really clear to me why the total is defined the way it is.

**Comment by SallyDa** [comment]
Can we close this too, or anything you still want us to do on this @JakobBD?

**Comment by JakobBD** [comment]
yes, can be closed.
