### ISSUE TITLE
More flexible low-code mixing of different data readers 

### ISSUE THREAD

**Issue by JakobBD** [pik-piam/sodym#23]
If I want to define the items of the dimensions in the code, and read parameters from csv, I should be able to do so without complex coding.

**Comment by SallyDa** [comment]
See documentation for sodym.dimensions.DimensionSet, where I have explicitly added this example. Not sure if you still think it's too complicated, but I would think that having such an example in a jupyter notebook as well would be sufficient?

**Comment by SallyDa** [comment]
I can see that having either more examples, or defining functions outside the datareader and then when defining your datareader you could basically take those functions from outside in whichever combination you like. Personally I still prefer to have all data reading defined in the same place (in the DataReader child you specify), but I think this links to the MFASystem discussion and how MFASystem instances should be initialised/defined and used. Maybe for a longer discussion then...

**Comment by JakobBD** [comment]
closed with #67
